Repository pimcore/output-data-config-toolkit, pull requests merged in 2023-05, with the labels that each got.

#91 Kick ecommerce bundle requirement
  composer.json
  src/ConfigElement/Value/DefaultValue.php
Labels: Task

#92 [Task]: Fix Docs
  README.md
  doc/ProductListSpecification.php
Labels: Task

#88 bugfix: prevent error when no childs are defined
  src/ConfigElement/Operator/TextAddon.php
Labels: Bug

#96 Pimcore 11 pre-release TODOs
  composer.json
Labels: Task

#97 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
Labels: sync

#99 [phpstan] re-enable running lowest dependencies action
  .github/workflows/static-analysis.yml
  composer.json
Labels: Task
