Repository pimcore/output-data-config-toolkit, pull requests merged in 2023-04, with the labels that each got.

#82 [Task] Added `ecommerce-framework-bundle` to composer
  composer.json
Labels: Task

#81 [Bug]: migration
  src/Migrations/Version20221130082116.php
Labels: Bug

#79 [Improvement] Added `PimcoreBundleAdminSupportInterface` to bundle class
  .github/workflows/static-analysis.yml
  src/OutputDataConfigToolkitBundle.php
Labels: Improvement

#80 [Task] Replace `Pimcore\File` methods with Filesystem
  src/Service.php
  src/Tools/Installer.php
Labels: Task

#84 Static Analysis - Add 11.x-dev matrix
  .github/workflows/static-analysis.yml
Labels: Task

#85 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/config/system.yml
Labels: sync

#86 [Task] Updated requirement for ecommerce-framework-bundle
  composer.json
Labels: Task

#87 Adapt admin bundle refactorings
  .github/ci/files/config/packages/security.yaml
  composer.json
  src/Controller/AdminController.php
  src/Controller/ClassController.php
  src/OutputDataConfigToolkitBundle.php
Labels: Task
